[package]
name = "hertz-knudsen-schrage"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = { version = "0.3.7", default-features = false, features = ["svg_backend", "line_series"] }
statrs = "0.18.0"
